### ISSUE TITLE
[Suggestion] Add config file.

### ISSUE THREAD

**Issue by cryptolake** [elfalehdev/setup_shift#3]
I think it would be better if all the settings are in a config file instead of being hardcoded, so it won't matter how many packages there are to be installed and the script would be more broad and general, i suggest you do this in yaml or a simple ini file.

**Comment by elfalehed** [comment]
can you explain it more? you need to have a config file that has all of the needed packages to download without writing python code for it? any idea how to do that? tutorial or docs

**Comment by cryptolake** [comment]
So instead of [Hard Coding](https://en.wikipedia.org/wiki/Hard_coding) you would loop in the packages listed in the config the user specifies and installs them like the [nix package manager](https://nixos.org/). check the yaml library for python.

**Comment by cryptolake** [comment]
Check my pull request #4  see what i mean you can build on top of it if you like.
